### ISSUE TITLE
Softlock Freeze while carrying Spears in Garbage Wastes (Artificer)

### ISSUE THREAD

**Issue by dalekfan** [SchuhBaum/InfiniteSpears#1] opened 2023-07-31 21:29 UTC
https://pastebin.com/MDByk6Y1

Exception Log here.

**Comment by SchuhBaum** [comment] 2023-08-01 02:18
I have a rough idea what might have happened. I added some more checks in v2.1.7. It should be impossible now. Let me know if the issue is fixed for you or not. Or you can also close the issue in the first case.

**Comment by dalekfan** [comment] 2023-08-01 06:05
> I have a rough idea what might have happened. I added some more checks in v2.1.7. It should be impossible now. Let me know if the issue is fixed for you or not. Or you can also close the issue in the first case.

Seems fixed. Map issue is still happening though.

**Closed as completed** 2023-08-05 18:45 UTC
